  name: Deploy to github pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v2
          with:
            version:  20.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Clean install dependencies
          run: npm ci
        - name: Setup Git 
          run: |
            git config --global user.email "jame.flochlecarour@gmail.com"
            git config --global user.name "JameFLC"
        - name: Deploy SvelteKit app
          run: npm run deploy
